### ISSUE TITLE
`Core dumped` when loading Wav audio

### ISSUE THREAD

**Issue by tree786isback** [krait-games/hyperion-engine#15]
Hello

I am trying to get some basic audio up and running in hyperion. I'm at the stage of trying to load in a wav audio file, but I am getting core dumped error when I run the following code:
```
  hyperion::AssetManager* asset = hyperion::AssetManager::GetInstance();
  asset->LoadFromFile<hyperion::Loadable>("../my_sound.wav");
```
Not sure if I'm doing something wrong? Do you also have a simple example of loading and playing audio in hyperion (I couldn't find one in the demo example)?

**Comment by tree786isback** [comment]
Here is the full error log FYI:
```
terminate called after throwing an instance of 'char const*'

Aborted (core dumped)
```

**Comment by ajmd17** [comment]
Hey there! Thanks for submitting this. 
Haven't had a chance to update some of the demo stuff lately as I've been working on a rewrite of the renderer for Vulkan. 

I suspect the core dumped might have something to do with the asset manager not finding the asset in the correct path, but that is just a guess. 
Can you see the value of the string that is being thrown? That may tell us some more here.

I'll be able to take a better look at this tomorrow but for now you could try something along the lines of this code below as a rudimentary example. There may be a few changes required here and there to make it work with your specific use case.


In your main initialization method:
```
// Initialize the audio manager
AudioManager::GetInstance()->Initialize();


// Add an AudioControl, provide it with an AudioSource (which is an instance of Loadable)
auto audio_ctrl = std::make_shared<AudioControl>(
            AssetManager::GetInstance()->LoadFromFile<AudioSource>("sounds/cartoon001.wav"));

// Add that AudioControl to your node so it is associated with a 3d space
my_node->AddControl(audio_ctrl);
audio_ctrl->GetSource()->SetLoop(true);
audio_ctrl->GetSource()->Play();

// Finally, add your node to the root node of the scene
GetScene()->AddChild(my_node);
```

Then in your Logic() method, set 3d audio position and orientation:
```
AudioManager::GetInstance()->SetListenerPosition(GetCamera()->GetTranslation());
AudioManager::GetInstance()->SetListenerOrientation(GetCamera()->GetDirection(), GetCamera()->GetUpVector());
```


Let me know if this is, or isn't any help to you. Cheers!

**Comment by ajmd17** [comment]
Ok, I have a slight suspicion of what is going on there but I'll have to confirm later. What platform are you currently running on? 

The issue may have something to do with `long` being used in the loader, rather than `uint32_t`, as Windows has a different size for that type than Unix based systems . I've pushed a hotfix but will wait until the morning here when I can confirm that it works as intended.
Thanks for catching this! And I appreciate the patience

**Comment by tree786isback** [comment]
Hi,

Thanks for the detailed response and examples! 
>In your main initialization method:

That's very helpful example, much appreciated !

>What platform are you currently running on?

I am running manjaro (unix-based)

> I've pushed a hotfix but will wait until the morning here when I can confirm that it works as intended.

Cool! I'll give it a shot and let you know of the result

**Comment by tree786isback** [comment]
I have just tested the latest commit, and it works great now! Thanks very much! :)

**Comment by tree786isback** [comment]
As a side question -- is there a way  to delete an audio source object from the world?

**Comment by ajmd17** [comment]
You may have to call `Stop()` on the `AudioSource` object, and then you should remove the `AudioControl` from your node. If you want to keep the audio control on the node, you can also do something like: `audio_ctrl->SetSource(nullptr)`. 

Just a note, due to the asset manager's caching system, the audio source object won't actually be de-allocated at that point. This will be changing pretty soon. As a part of the rewrite, we've been getting away from the heavy usage of `shared_ptr`s. I suppose another option would be to change the cache system to use `weak_ptr` internally.

**Comment by tree786isback** [comment]
Ah ok, thanks for the explanation!

**Comment by ajmd17** [comment]
No problem!
